<?php 
    $text1 = "Crowe interpreta il fedele generale Massimo, che viene tradito quando Commodo, l'ambizioso figlio dell'imperatore Marco Aurelio, assassina il padre e s'impossessa del trono. Ridotto in schiavitù, Massimo ricompare nell'arena tra le file dei gladiatori per vendicare l'assassinio della sua famiglia e del suo imperatore."; 

    $text2 = "1876. Nathan Algren, ex capitano dell'esercito statunitense e veterano del Settimo Cavalleria che lavora pubblicizzando i fucili Winchester, riceve la proposta di addestrare l'esercito dell'imperatore giapponese Meiji allo scopo di eliminare i samurai ribelli. Il reduce accetta la missione, che vede solo come un modo per far soldi e fuggire dall'atroce ricordo delle guerre indiane (che peraltro lo ha spinto all'alcolismo), e arrivato in Giappone trova un Paese nel pieno dello scontro tra la frenetica corsa alla modernità voluta dal giovane imperatore e una cultura millenaria legata alla filosofia del Bushido."; 

    $text3 = "1757: durante la guerra tra francesi e inglesi in Nord America (il teatro nord-americano della guerra dei sette anni) si svolgono le vicende di una famiglia di nativi americani (delle tribù dei Mohicani) composta da Chingachgook, suo figlio Uncas e il bianco Nathan Occhio di Falco, orfano di genitori inglesi e adottato in tenera età da Chingachgook. Il gruppo è in fuga dalla guerra verso le pianure occidentali.

    Un tenente reclutatore inglese assolda volontari tra i nativi di un villaggio, tappa di passaggio per i tre mohicani che rifiutano e proseguono nel loro viaggio. I tre raggiungono e salvano una compagnia inglese da un'imboscata della tribù Urone comandata dal feroce Magua: l'attacco era una vendetta di natura personale verso il comandante inglese Munro, reo di aver causato la morte dei suoi figli. La compagnia era di scorta alle figlie di Munro, Cora e Alice, di cui Nathan e Uncas si innamorano, accettando di seguirle nella loro destinazione. Nel tragitto osservano le conseguenze delle campagne di reclutamento inglese, motivo di faide e stragi reciproche tra le tribù native.
    
    Munro è asserragliato sotto un logorante assedio francese e ormai prossimo alla resa, ma il colonnello confida nell'arrivo imminente di rinforzi e impone la resistenza a oltranza. Sarà l'affetto per Cora e Alice, ora divenuto un sincero amore, a motivare Nathan e Uncas per spingere a una tregua che permetta una riappacificazione tra le tribù native.
    
    Avuta notizia che i rinforzi non arriveranno, il colonnello Munro stipula una tregua con i francesi guidati dal generale Montcalm e abbandona il forte con l'onore delle armi, ma Magua e i suoi tribù Urone attaccano a sorpresa gli inglesi, scontenti dell'esito delle trattative: nello scontro Magua uccide personalmente Munro, mentre i mohicani, Hayward e le figlie di Munro riescono a fuggire. Le ragazze e l’ufficiale vengono catturate in un secondo momento: Nathan offre subito la sua vita al capotribù urone Sakem in cambio della libertà per l’amata Cora; anche Hayward, però, ormai capito che il suo amore per Cora non verrà mai corrisposto, offre la sua vita in cambio di quella della ragazza. Il capo urone infatti, decide che Cora debba vivere e quindi viene consegnata a Nathan, che Hayward debba morire e che Alice debba diventare la moglie di Magua. Il mohicano Uncas viene ucciso da Magua nel tentativo di salvare l'amata Alice che, disperata, si suicida. Arrivano Nathan e Chingachgook, e quest'ultimo affronta Magua e lo uccide in un duello. Il film si conclude con i funerali di Uncas e con un ultimo discorso di Chingachgook, che dopo aver vendicato il figlio, è ormai rimasto l'ultimo dei Mohicani."; 

?>