<?php 
    $text1 = "Crowe interpreta il fedele generale Massimo, che viene tradito quando Commodo, l'ambizioso figlio dell'imperatore Marco Aurelio, assassina il padre e s'impossessa del trono. Ridotto in schiavitù, Massimo ricompare nell'arena tra le file dei gladiatori per vendicare l'assassinio della sua famiglia e del suo imperatore."; 

    $text2 = "1876. Nathan Algren, ex capitano dell'esercito statunitense e veterano del Settimo Cavalleria che lavora pubblicizzando i fucili Winchester, riceve la proposta di addestrare l'esercito dell'imperatore giapponese Meiji allo scopo di eliminare i samurai ribelli. Il reduce accetta la missione, che vede solo come un modo per far soldi e fuggire dall'atroce ricordo delle guerre indiane (che peraltro lo ha spinto all'alcolismo), e arrivato in Giappone trova un Paese nel pieno dello scontro tra la frenetica corsa alla modernità voluta dal giovane imperatore e una cultura millenaria legata alla filosofia del Bushido."; 

    $text3 = "1757: durante la guerra tra francesi e inglesi in Nord America (il teatro nord-americano della guerra dei sette anni) si svolgono le vicende di una famiglia di nativi americani (delle tribù dei Mohicani) composta da Chingachgook, suo figlio Uncas e il bianco Nathan Occhio di Falco, orfano di genitori inglesi e adottato in tenera età da Chingachgook. Il gruppo è in fuga dalla guerra verso le pianure occidentali.

    Un tenente reclutatore inglese assolda volontari tra i nativi di un villaggio, tappa di passaggio per i tre mohicani che rifiutano e proseguono nel loro viaggio. I tre raggiungono e salvano una compagnia inglese da un'imboscata della tribù Urone comandata dal feroce Magua: l'attacco era una vendetta di natura personale verso il comandante inglese Munro, reo di aver causato la morte dei suoi figli. La compagnia era di scorta alle figlie di Munro, Cora e Alice, di cui Nathan e Uncas si innamorano, accettando di seguirle nella loro destinazione. Nel tragitto osservano le conseguenze delle campagne di reclutamento inglese, motivo di faide e stragi reciproche tra le tribù native.
    
    Munro è asserragliato sotto un logorante assedio francese e ormai prossimo alla resa, ma il colonnello confida nell'arrivo imminente di rinforzi e impone la resistenza a oltranza. Sarà l'affetto per Cora e Alice, ora divenuto un sincero amore, a motivare Nathan e Uncas per spingere a una tregua che permetta una riappacificazione tra le tribù native.
    
    Avuta notizia che i rinforzi non arriveranno, il colonnello Munro stipula una tregua con i francesi guidati dal generale Montcalm e abbandona il forte con l'onore delle armi, ma Magua e i suoi tribù Urone attaccano a sorpresa gli inglesi, scontenti dell'esito delle trattative: nello scontro Magua uccide personalmente Munro, mentre i mohicani, Hayward e le figlie di Munro riescono a fuggire. Le ragazze e l’ufficiale vengono catturate in un secondo momento: Nathan offre subito la sua vita al capotribù urone Sakem in cambio della libertà per l’amata Cora; anche Hayward, però, ormai capito che il suo amore per Cora non verrà mai corrisposto, offre la sua vita in cambio di quella della ragazza. Il capo urone infatti, decide che Cora debba vivere e quindi viene consegnata a Nathan, che Hayward debba morire e che Alice debba diventare la moglie di Magua. Il mohicano Uncas viene ucciso da Magua nel tentativo di salvare l'amata Alice che, disperata, si suicida. Arrivano Nathan e Chingachgook, e quest'ultimo affronta Magua e lo uccide in un duello. Il film si conclude con i funerali di Uncas e con un ultimo discorso di Chingachgook, che dopo aver vendicato il figlio, è ormai rimasto l'ultimo dei Mohicani."; 

    $text4 = "Nel pieno della seconda guerra mondiale, il brillante matematico Alan Turing decide di mettere le proprie capacità al servizio del governo della Gran Bretagna. L'obiettivo è far terminare il conflitto quanto prima, collaborando alla segretissima operazione di decrittazione dei messaggi segreti nazisti, codificati con la macchina denominata Enigma. Metodico e silenzioso, Turing si presenta al colloquio e convince il Comandante Alastair Denniston, dimostrando le sue capacità, ad assumerlo nonostante non conosca il tedesco, ma i primi dissapori cominciano a manifestarsi quando comprende che non dovrà lavorare da solo, ma con altre brillanti menti matematiche. Caratterialmente solitario e pignolo sul lavoro, Turing comincia a diventare antipatico ai suoi collaboratori e al suo capo Hugh Alexander (campione nazionale e maestro di scacchi). Decifrare i codici codificati della macchina Enigma è una missione ritenuta impossibile da chiunque, in particolare dalle autorità britanniche, in quanto si tratta di un dispositivo estremamente complesso, che presenta un'enorme quantità di possibili chiavi di codificazione dei messaggi, e i tedeschi cambiano la chiave di codificazione ogni 24 ore, allo scoccare della mezzanotte di ogni giorno.

    Divenuto capo del gruppo, con non pochi attriti con il suo datore di lavoro e con il sostegno del capo dell'MI6 Stewart Menzies, Turing decide che è giunto il momento di cambiare metodo: non più agire in difesa tentando di capire giorno per giorno quale sia la chiave usata al momento nei codici, ma giocare al contrattacco e realizzare una macchina che decifri automaticamente ogni singolo messaggio. Alan seleziona quindi tra i migliori candidati coloro che dovranno accompagnarlo nell'impresa di costruire la macchina elaboratrice che renda comprensibili i messaggi nemici. Chi fosse riuscito a risolvere un cruciverba da lui inventato (pubblicato su un giornale) in non più di dieci minuti si sarebbe dovuto presentare alle selezioni per l'incarico segreto; tra i candidati si trova la venticinquenne Joan Clarke, ancora nubile e appassionata di logica e matematica, che svolge l'esame con una rapidità che batte quella dello stesso Turing (ai candidati viene assegnato un cruciverba da svolgere in un tempo massimo di sei minuti, cosa che Turing ritiene impossibile dal momento che lui ne impiegherebbe circa otto, e la Clarke è l'unica a finire prima dello scadere del tempo). A questo punto Turing scrive una lettera a Winston Churchill spiegandogli il suo progetto e chiedendogli un finanziamento di centomila sterline, che gli verrà immediatamente concesso, per costruire la macchina che impedirà ai tedeschi di invadere il resto dell'Europa. Nel frattempo i nemici del matematico pianificano di toglierlo di mezzo investigando sul suo passato (nel quale Turing era continuamente oggetto di scherzi e prese in giro da parte dei suoi compagni di scuola) e usando qualsiasi cosa come pretesto per toglierlo dalla circolazione; il povero Alan viene dapprima accusato di essere una spia sovietica e poi minacciato di essere sbattuto fuori dal progetto con la scusa che la macchina da lui ideata sta funzionando da giorni e non ha ancora prodotto risultati soddisfacenti."

?>